services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: flask_app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "5000:5000"
      - "6790:6790" 
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
